version: '3'
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    env_file: .env
    networks:
      - fitness-gpt
    volumes:
      - ${PWD}:/app

  fitnessdb:
    container_name: fitnessdb
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    #env_file: .env
    image: postgres:12.0-alpine
    environment:
      PGUSER: ${DATABASE_USERNAME}
      PGDATABASE: ${DATABASE_PASSWORD}
    volumes:
      #- fitness-data:/var/lib/postgresql/data/ #using a volume
      - ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - '5432:5432'
    networks:
      - fitness-gpt

volumes:
  fitness-data:

networks:
  fitness-gpt:
    name: FitnessGPT
    driver: bridge
