# Stage 1: Build the app
FROM node:18 AS build

#USER root
# Set the working directory
WORKDIR /app
#RUN chown -R 1001:1001 /app
#USER 1001

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose the desired port
EXPOSE 3000

# Start the app
CMD ["npm", "run", "dev"]
