##### DEPENDENCIES

FROM --platform=linux/amd64 node:16-alpine3.17 AS builder
RUN apk add --no-cache libc6-compat openssl1.1-compat
RUN yarn global add pnpm
ARG DATABASE_URL
ARG NEXT_PUBLIC_CLIENTVAR
ENV NODE_ENV development
WORKDIR /app
EXPOSE 3000
ENV PORT 3000
COPY start-local-dev.sh start-local-dev.sh
CMD [ "/app/start-local-dev.sh" ]







